using Domain.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Persistance.Date
{
    public class StoreDbContext : DbContext
    {

            public StoreDbContext(DbContextOptions<StoreDbContext> options) : base(options)
            {
            }

            public DbSet<Product> Products { get; set; }
            public DbSet<ProductBrand> ProductBrands { get; set; }
            public DbSet<ProductType> ProductTypes { get; set; }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                // Apply configurations from all assemblies
                modelBuilder.ApplyConfigurationsFromAssembly(typeof(AssemblyReference).Assembly);

                // Ensure the Product entity's Id is auto-generated by the database
                modelBuilder.Entity<Product>()
                    .Property(p => p.Id)
                    .ValueGeneratedOnAdd(); // Tells EF to auto-generate the Id


                base.OnModelCreating(modelBuilder);
            }


        }


}
